apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: test
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "2"
