apiVersion: v1
kind: Namespace
metadata:
  name: test-trivy-ns
  labels:
    name: test-trivy-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-inseguro
  namespace: test-trivy-ns
spec:
  hostNetwork: true
  containers:
  - name: nginx-inseguro
    image: nginx:alpine3.17
    securityContext:
      privileged: true