apiVersion: v1
kind: Namespace
metadata:
  name: test-secrets-ns
  labels:
    name: test-secrets-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-secrets-sa
  namespace: test-secrets-ns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/tfm-asaldana-secret-role
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-secrets-aws
  namespace: test-secrets-ns
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "tfm-asaldana-secret"
          objectType: "secretsmanager"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-secrets-pod
  namespace: test-secrets-ns
spec:
  serviceAccountName: test-secrets-sa
  volumes:
    - name: test-secrets-aws
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "test-secrets-aws"
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - "sleep"
      - "86400"
    volumeMounts:
      - name: test-secrets-aws
        mountPath: "/mnt/aws-secrets-store"
        readOnly: true
    securityContext:
      readOnlyRootFilesystem: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.25"
      requests:
        memory: "128Mi"
        cpu: "0.25"
